// Gate tests for BERNARD_optimise, against the function deployed in the
// workflow. tests/optimise-gates.live.js is generated by
// scripts/build-optimise-workflows.py from the same string that ships to n8n,
// so these run against what is deployed, not a copy. Same discipline as
// parse-batch.
//
// Run: node tests/optimise-gates.test.js
const runGates = require("./optimise-gates.live.js");

const CFG = {
  enabled: true,
  account_ids: ["act_1766396370547849"],
  write_budget: { max_mutations: 25, max_daily_budget_minor: 20000 },
  optimise: { thrash_n: 4, daily_ceiling: 3, budget_max_delta_pct: 25 },
};
const OUR_APP = "1023714696912738";

const base = (over) => ({
  body: {
    account_id: "act_1766396370547849",
    moves: [{ op: "pause", entity_type: "ad", entity_id: "120", evidence: "spent $80 across 14 days, zero purchases, CPA 4x account median" }],
    ...((over && over.body) || {}),
  },
  cfg: over && "cfg" in over ? over.cfg : CFG,
  counts: { executed_today: 0, our_changes_7d: {}, ...((over && over.counts) || {}) },
  activities: (over && over.activities) || [],
  nowIso: "2026-08-18T12:00:00Z",
});

let pass = 0, fail = 0;
const check = (name, cond, detail) => {
  if (cond) { pass++; console.log(`  ok    ${name}`); }
  else { fail++; console.log(`  FAIL  ${name}${detail ? "\n          " + JSON.stringify(detail) : ""}`); }
};

// config gates
{
  check("no config refuses", runGates(base({ cfg: null })).gate === "config");
  check("disabled refuses", runGates(base({ cfg: { ...CFG, enabled: false } })).gate === "enabled");
  check("stand_down refuses", runGates(base({ cfg: { ...CFG, stand_down: true } })).gate === "stand_down");
  check("kill_switch refuses", runGates(base({ cfg: { ...CFG, kill_switch: true } })).gate === "kill_switch");
  const r = runGates(base({ body: { account_id: "act_999" } }));
  check("account off allow-list refuses", r.gate === "allowlist", r);
}

// ceiling
{
  check("ceiling reached refuses", runGates(base({ counts: { executed_today: 3 } })).gate === "ceiling");
  const r = runGates(base({
    counts: { executed_today: 2 },
    body: { moves: [
      { op: "pause", entity_type: "ad", entity_id: "1", evidence: "long enough evidence string" },
      { op: "pause", entity_type: "ad", entity_id: "2", evidence: "long enough evidence string" }] },
  }));
  check("2 proposed with 1 slot left refuses", r.gate === "ceiling", r);
  check("1 proposed with 1 slot left passes", runGates(base({ counts: { executed_today: 2 } })).ok === true);
}

// grammar
{
  check("unknown op fails the set", runGates(base({ body: { moves: [{ op: "retarget", entity_type: "ad", entity_id: "1", evidence: "evidence long enough" }] } })).gate === "grammar");
  check("empty evidence refuses", runGates(base({ body: { moves: [{ op: "pause", entity_type: "ad", entity_id: "1", evidence: "" }] } })).gate === "grammar");
  const dup = runGates(base({ body: { moves: [
    { op: "pause", entity_type: "ad", entity_id: "1", evidence: "evidence long enough here" },
    { op: "budget", entity_type: "adset", entity_id: "1", from_minor: 4000, to_minor: 3000, evidence: "evidence long enough here" }] } }));
  check("two moves on one entity refuses", dup.gate === "grammar", dup);
}

// budget bounds
{
  const over = runGates(base({ body: { moves: [{ op: "budget", entity_type: "adset", entity_id: "9", from_minor: 4000, to_minor: 5100, evidence: "evidence long enough here" }] } }));
  check("budget +27.5% exceeds the ±25% bound", over.gate === "budget_bound", over);
  const okUp = runGates(base({ body: { moves: [{ op: "budget", entity_type: "adset", entity_id: "9", from_minor: 4000, to_minor: 5000, evidence: "evidence long enough here" }] } }));
  check("budget +25% exactly passes", okUp.ok === true, okUp);
  const cap = runGates(base({ body: { moves: [{ op: "budget", entity_type: "adset", entity_id: "9", from_minor: 19000, to_minor: 22000, evidence: "evidence long enough here" }] } }));
  check("to_minor above max_daily_budget_minor refuses", cap.gate === "budget_bound", cap);
}

// thrash: platform history and our snapshots count together
{
  const acts = (n, entity, app) => Array.from({ length: n }, (_, i) => ({
    object_id: entity, event_type: "update_ad_run_status",
    event_time: "2026-08-1" + (i % 7 + 1), actor_name: "Freelancer", application_id: app || null,
  }));
  const r = runGates(base({ activities: acts(3, "120"), counts: { executed_today: 0, our_changes_7d: { 120: 1 } } }));
  check("3 freelancer + 1 ours = 4 = thrash refusal", r.gate === "thrash", r);
  const under = runGates(base({ activities: acts(2, "120"), counts: { executed_today: 0, our_changes_7d: { 120: 1 } } }));
  check("3 total changes passes at threshold 4", under.ok === true, under);
  const other = runGates(base({ activities: acts(10, "999") }));
  check("thrash on another entity does not block this one", other.ok === true, other);
}

// human-change check: flags, never blocks
{
  const r = runGates(base({ activities: [
    { object_id: "120", event_type: "update_ad_run_status", event_time: "2026-08-16", actor_name: "Baptiste J", application_id: "555" }] }));
  check("human change flags, does not block", r.ok === true && !!r.staged[0].human_change_conflict, r);
  check("flag names the human", r.staged[0].human_change_conflict.includes("Baptiste J"), r.staged[0]);
  const ours = runGates(base({ activities: [
    { object_id: "120", event_type: "update_ad_run_status", event_time: "2026-08-16", actor_name: "system", application_id: OUR_APP }] }));
  check("our own app's change does not flag as human", ours.ok === true && !ours.staged[0].human_change_conflict, ours);
}

// unreadable change history fails closed, after the config gates
{
  const r = runGates({ ...base({}), activities: null });
  check("unreadable change history fails closed", r.gate === "change_history", r);
  const bad = runGates({ ...base({ body: { account_id: "act_999" } }), activities: null });
  check("allowlist still wins over unreadable history", bad.gate === "allowlist", bad);
}

// happy path carries the flags forward
{
  const r = runGates(base({}));
  check("happy path passes", r.ok === true);
  check("immature-data flag always set in v1", r.immature_data === true);
}

console.log(`\n  ${pass} passed, ${fail} failed\n`);
process.exit(fail ? 1 : 0);
