// Diff tests for the v1.1 exclusion write verification, against the function
// deployed in BERNARD_optimise_execute. tests/verify-exclusion.live.js is
// generated by scripts/build-optimise-workflows.py from the same string that
// ships to n8n, so these run against what is deployed, not a copy. Same
// discipline as optimise-gates.
//
// This is acceptance tests 1 and 2 of BERNARD_OPTIMISE_V1_1_EXCLUSIONS_SPEC.md
// at logic level: an unchanged-everywhere-else round trip verifies, and a
// partial payload (any other field changed or dropped) is verification_failed
// with zero silent success.
//
// Run: node tests/verify-exclusion.test.js
const verify = require("./verify-exclusion.live.js");

const AUD = "120250694850660053";
const SNAP = {
  age_min: 25,
  age_max: 55,
  geo_locations: { countries: ["DE"], location_types: ["home", "recent"] },
  custom_audiences: [{ id: "111", name: "Site visitors 30d" }],
  excluded_custom_audiences: [{ id: "222", name: "Existing exclusion" }],
  targeting_relaxation_types: { custom_audience: 1, lookalike: 0 },
  publisher_platforms: ["facebook", "instagram"],
};
// Meta reads back {id, name} entries; the diff must compare by id, not by shape.
const goodReadback = {
  ...JSON.parse(JSON.stringify(SNAP)),
  excluded_custom_audiences: [
    { id: "222", name: "Existing exclusion" },
    { id: AUD, name: "Applicants and Bookers" },
  ],
};

let pass = 0, fail = 0;
const check = (name, cond, detail) => {
  if (cond) { pass++; console.log(`  ok    ${name}`); }
  else { fail++; console.log(`  FAIL  ${name}${detail ? "\n          " + JSON.stringify(detail) : ""}`); }
};

// the clean round trip verifies
{
  const p = verify(SNAP, goodReadback, AUD);
  check("clean round trip has zero problems", p.length === 0, p);
}

// key-order noise must not fail verification (Meta does not promise key order)
{
  const reordered = JSON.parse(JSON.stringify(goodReadback));
  reordered.geo_locations = { location_types: ["home", "recent"], countries: ["DE"] };
  const p = verify(SNAP, reordered, AUD);
  check("re-ordered object keys still verify", p.length === 0, p);
}

// partial payloads: every dropped or mutated field is caught
{
  const dropped = JSON.parse(JSON.stringify(goodReadback));
  delete dropped.custom_audiences;
  const p1 = verify(SNAP, dropped, AUD);
  check("dropped inclusion list is caught", p1.some((x) => x.includes('"custom_audiences"')), p1);

  const mutated = JSON.parse(JSON.stringify(goodReadback));
  mutated.age_min = 18;
  const p2 = verify(SNAP, mutated, AUD);
  check("mutated age_min is caught", p2.some((x) => x.includes('"age_min"')), p2);

  const geoGone = JSON.parse(JSON.stringify(goodReadback));
  delete geoGone.geo_locations;
  const p3 = verify(SNAP, geoGone, AUD);
  check("dropped geo is caught", p3.some((x) => x.includes('"geo_locations"')), p3);

  const flagGone = JSON.parse(JSON.stringify(goodReadback));
  delete flagGone.targeting_relaxation_types;
  const p4 = verify(SNAP, flagGone, AUD);
  check("dropped Advantage flag is caught", p4.some((x) => x.includes('"targeting_relaxation_types"')), p4);
}

// the exclusion itself must have landed, exactly once
{
  const unchanged = JSON.parse(JSON.stringify(SNAP));
  const p1 = verify(SNAP, unchanged, AUD);
  check("audience not added is caught", p1.some((x) => x.includes("identical to pre-write")), p1);

  const wrongAud = JSON.parse(JSON.stringify(goodReadback));
  wrongAud.excluded_custom_audiences[1].id = "999999999";
  const p2 = verify(SNAP, wrongAud, AUD);
  check("wrong audience added is caught", p2.length > 0, p2);

  const lostExisting = JSON.parse(JSON.stringify(goodReadback));
  lostExisting.excluded_custom_audiences = [{ id: AUD }];
  const p3 = verify(SNAP, lostExisting, AUD);
  check("existing exclusion silently dropped is caught", p3.length > 0, p3);
}

// no read-back at all is a failure, never a pass
{
  const p = verify(SNAP, null, AUD);
  check("missing read-back fails", p.length > 0, p);
}

// empty pre-write exclusion list: first exclusion on a clean ad set
{
  const cleanSnap = { ...JSON.parse(JSON.stringify(SNAP)) };
  delete cleanSnap.excluded_custom_audiences;
  const rb = { ...JSON.parse(JSON.stringify(cleanSnap)), excluded_custom_audiences: [{ id: AUD }] };
  const p = verify(cleanSnap, rb, AUD);
  check("first exclusion on a clean ad set verifies", p.length === 0, p);
}

console.log(`\n  ${pass} passed, ${fail} failed\n`);
process.exit(fail ? 1 : 0);
