// Diff tests for the v1.2 placement write verification, against the function
// deployed in BERNARD_optimise_execute (tests/verify-placement.live.js is
// generated by scripts/build-optimise-workflows.py from the same string that
// ships to n8n). Same discipline as verify-exclusion: only the named platform
// removal may differ from the pre-write snapshot; anything else is
// verification_failed, never silent success.
//
// Run: node tests/verify-placement.test.js
const verify = require("./verify-placement.live.js");

const SNAP = {
  age_min: 25,
  age_max: 65,
  geo_locations: { countries: ["US", "CA"] },
  custom_audiences: [{ id: "111", name: "Site visitors" }],
  publisher_platforms: ["facebook", "instagram", "audience_network"],
  facebook_positions: ["feed", "facebook_reels"],
  instagram_positions: ["stream", "reels"],
  audience_network_positions: ["classic"],
  device_platforms: ["mobile", "desktop"],
};
const good = () => {
  const rb = JSON.parse(JSON.stringify(SNAP));
  rb.publisher_platforms = ["facebook", "instagram"];
  delete rb.audience_network_positions;
  return rb;
};

let pass = 0, fail = 0;
const check = (name, cond, detail) => {
  if (cond) { pass++; console.log(`  ok    ${name}`); }
  else { fail++; console.log(`  FAIL  ${name}${detail ? "\n          " + JSON.stringify(detail) : ""}`); }
};

// clean removal verifies
{
  const p = verify(SNAP, good(), "audience_network");
  check("clean platform removal has zero problems", p.length === 0, p);
}

// the platform must actually be gone
{
  const unchanged = JSON.parse(JSON.stringify(SNAP));
  const p = verify(SNAP, unchanged, "audience_network");
  check("platform not removed is caught", p.some((x) => x.includes("was not removed")), p);
}

// removing the wrong platform is caught
{
  const rb = JSON.parse(JSON.stringify(SNAP));
  rb.publisher_platforms = ["facebook", "audience_network"]; // instagram gone instead
  const p = verify(SNAP, rb, "audience_network");
  check("wrong platform removed is caught", p.length > 0, p);
}

// a lingering positions field for the removed platform is caught
{
  const rb = good();
  rb.audience_network_positions = ["classic"];
  const p = verify(SNAP, rb, "audience_network");
  check("lingering positions field is caught", p.some((x) => x.includes("audience_network_positions")), p);
}

// any OTHER field changing is caught (the replace-not-merge hazard)
{
  const rb = good();
  delete rb.custom_audiences;
  const p1 = verify(SNAP, rb, "audience_network");
  check("dropped audiences are caught", p1.some((x) => x.includes('"custom_audiences"')), p1);

  const rb2 = good();
  rb2.age_min = 18;
  const p2 = verify(SNAP, rb2, "audience_network");
  check("mutated age is caught", p2.some((x) => x.includes('"age_min"')), p2);

  const rb3 = good();
  delete rb3.device_platforms;
  const p3 = verify(SNAP, rb3, "audience_network");
  check("dropped device platforms are caught", p3.some((x) => x.includes('"device_platforms"')), p3);
}

// untouched platforms' positions fields must survive
{
  const rb = good();
  delete rb.facebook_positions;
  const p = verify(SNAP, rb, "audience_network");
  check("dropped facebook positions are caught", p.some((x) => x.includes('"facebook_positions"')), p);
}

// no read-back at all is a failure
{
  const p = verify(SNAP, null, "audience_network");
  check("missing read-back fails", p.length > 0, p);
}

console.log(`\n  ${pass} passed, ${fail} failed\n`);
process.exit(fail ? 1 : 0);
